package org.telegram.spybot.utils;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Random;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class SpyBotUtils {

    public static final String SPY_TEXT_RU = "Шпион";
    public static final List<String> COUNTRIES = List.of(
            "China",
            "India",
            "United States",
            "Indonesia",
            "Pakistan",
            "Brazil",
            "Nigeria",
            "Bangladesh",
            "Russia",
            "Mexico",
            "Japan",
            "Ethiopia",
            "Philippines",
            "Egypt",
            "Vietnam",
            "DR Congo",
            "Turkey",
            "Iran",
            "Germany",
            "Thailand",
            "United Kingdom",
            "France",
            "Italy",
            "Tanzania",
            "South Africa",
            "Myanmar",
            "Kenya",
            "South Korea",
            "Colombia",
            "Spain",
            "Uganda",
            "Argentina",
            "Algeria",
            "Sudan",
            "Ukraine",
            "Iraq",
            "Afghanistan",
            "Poland",
            "Canada",
            "Morocco",
            "Saudi Arabia",
            "Uzbekistan",
            "Peru",
            "Angola",
            "Malaysia",
            "Mozambique",
            "Ghana",
            "Yemen",
            "Nepal",
            "Venezuela",
            "Madagascar",
            "Cameroon",
            "Côte d'Ivoire",
            "North Korea",
            "Australia",
            "Niger",
            "Taiwan",
            "Sri Lanka",
            "Burkina Faso",
            "Mali",
            "Romania",
            "Malawi",
            "Chile",
            "Kazakhstan",
            "Zambia",
            "Guatemala",
            "Ecuador",
            "Syria",
            "Netherlands",
            "Senegal",
            "Cambodia",
            "Chad",
            "Somalia",
            "Zimbabwe",
            "Guinea",
            "Rwanda",
            "Benin",
            "Burundi",
            "Tunisia",
            "Bolivia",
            "Belgium",
            "Haiti",
            "Cuba",
            "South Sudan",
            "Dominican Republic",
            "Czech Republic",
            "Greece",
            "Jordan",
            "Portugal",
            "Azerbaijan",
            "Sweden",
            "Honduras",
            "United Arab Emirates",
            "Hungary",
            "Tajikistan",
            "Belarus",
            "Austria",
            "Papua New Guinea",
            "Serbia",
            "Israel",
            "Switzerland",
            "Togo",
            "Sierra Leone",
            "Laos",
            "Paraguay",
            "Bulgaria",
            "Libya",
            "Lebanon",
            "Nicaragua",
            "Kyrgyzstan",
            "El Salvador",
            "Turkmenistan",
            "Singapore",
            "Denmark",
            "Finland",
            "Slovakia",
            "Norway",
            "Oman",
            "State of Palestine",
            "Costa Rica"
    );

    public static String getRandomCountry(Random random) {
        return COUNTRIES.get(random.nextInt(COUNTRIES.size()));
    }
}
